[23기 박종규] 찜하기 기능 (GET, POST, DELETE)
wecode-bootcamp-korea/23-1st-ChickenFood-backend pull request #10
Opened 2021-08-10 01:57 UTC by dwenpark

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 찜하기 리스트 보기
- 찜하기, 찜하기 취소
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
<img width="571" alt="스크린샷 2021-08-10 오전 10 48 58" src="https://user-images.githubusercontent.com/80210205/128796788-c7f6e0ee-5454-4fdb-92af-e52456405880.png">
<img width="535" alt="스크린샷 2021-08-10 오전 10 49 06" src="https://user-images.githubusercontent.com/80210205/128796796-f5dcb132-8e2d-408c-ac51-c6ee811ae154.png">
<img width="553" alt="스크린샷 2021-08-10 오전 10 49 14" src="https://user-images.githubusercontent.com/80210205/128796800-97612e41-8e36-4420-b5d9-525e93a8a1c5.png">

- 찜하기 시에 DB내에서 Product에 좋아요 갯수가 추가, 삭제될 수 있도록 F() 객체 이용

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-10 10:35 UTC, Kang-kyunghun requested changes

2021-08-10 10:35 UTC, Kang-kyunghun commented on likes/views.py
> +        product.like_number = F("like_number") + 1
```suggestion
        product.like_number +=  1
```
혹시 이렇게는 안 되나요?? 
F를 안 써도 될 것 같아서요

2021-08-10 12:41 UTC, dwenpark commented on likes/views.py
> +        product.like_number = F("like_number") + 1
F객체 없애서 다시 푸쉬했습니다!!

2021-08-11 01:53 UTC, Kang-kyunghun commented
LGTM~~!!

2021-08-11 01:53 UTC, merged