[23기 박종규] 마이페이지 접속시 사용자 이름 호출 API
wecode-bootcamp-korea/23-1st-ChickenFood-backend pull request #13
Opened 2021-08-11 02:23 UTC by dwenpark

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 마이페이지 접속 시에 사용자 이름을 호출하는 API
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-11 10:19 UTC, Kang-kyunghun requested changes

2021-08-11 10:19 UTC, Kang-kyunghun commented on members/views.py
> +        info = {
```suggestion
        information = {
```
wecode에서는 단어를 줄여 쓰는 것을 지양하고 있습니다.

2021-08-11 10:19 UTC, Kang-kyunghun commented on members/views.py
> +        return JsonResponse({"INFO": info}, status=200)
```suggestion
        return JsonResponse({"result": information}, status=200)
```
or
```suggestion
        return JsonResponse({"data": information}, status=200)
```

2021-08-11 12:16 UTC, dwenpark commented on members/views.py
> +        return JsonResponse({"INFO": info}, status=200)
해당 사항 반영했습니다!

2021-08-11 12:16 UTC, dwenpark commented on members/views.py
> +        info = {
해당 사항 반영했습니다!

2021-08-12 00:50 UTC, Kang-kyunghun commented
LGTM~~!

2021-08-12 00:50 UTC, merged