ADD: 상품 리스트 페이지 view 작성
wecode-bootcamp-korea/23-1st-ChickenFood-backend pull request #4
Opened 2021-08-05 06:58 UTC by dwenpark

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- quary parameter별 filtering 적용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- /products/catalog : 전체 상품 호출 (catalogs은 null)
- /products/catalog?filter=brand : brand 호출 및 brand별 상품 호출 (기본값:  첫번째 브랜드 상품 호출)
- /products/catalog?filter=type : type 호출 및 type별 상품 호출 (기본값:  첫번째 타입 상품 호출)
- /products/catalog?filter=best : 전체 상품에서 좋아요 많은 순으로 호출 (catalogs은 null)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 브랜드 별 호출의 경우, 브랜드에 대한 이미지 및 이름은 계속 server와 통신이 되어야 하는 것 같은데,
  browser에서 중복되는 정보를 제외하고 통신하나요?
  자동으로 중복 데이터를 처리하지 않는다면,
  어떤 방법으로 중복되는 정보를 필터링하고 통신할 수 있을까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-05 07:00 UTC, dwenpark commented
<img width="1351" alt="스크린샷 2021-08-05 오후 4 00 09" src="https://user-images.githubusercontent.com/80210205/128305883-ad3ab5d2-4935-403f-901e-3d1da8759cb1.png">
<img width="1352" alt="스크린샷 2021-08-05 오후 3 59 43" src="https://user-images.githubusercontent.com/80210205/128305890-bf2fe5e6-e601-474b-ba73-e245ccd8c364.png">

2021-08-05 09:47 UTC, dwenpark commented
<img width="1348" alt="스크린샷 2021-08-05 오후 6 47 01" src="https://user-images.githubusercontent.com/80210205/128329971-32c28985-110f-4cb5-95a5-95ede1cd9757.png">
<img width="1344" alt="스크린샷 2021-08-05 오후 6 47 14" src="https://user-images.githubusercontent.com/80210205/128329980-a70dbdf0-ca0c-40e4-aa80-752df1523fbc.png">

2021-08-06 02:08 UTC, Kang-kyunghun requested changes

2021-08-06 02:08 UTC, Kang-kyunghun commented on brand.csv
> +E,5
.csv 과 upload.py 파일은 github에 올라오면 안 되는 파일들입니다. gitignore에 추가해 주시고 PR에서 제거해 주세요.

2021-08-06 02:08 UTC, Kang-kyunghun commented
view에 관련해서는 제가 따로 만나서 이야기 드리겠습니다.

2021-08-06 05:35 UTC, Kang-kyunghun requested changes

2021-08-06 05:35 UTC, Kang-kyunghun commented on products/views.py
> +            products = Product.objects.all().order_by("id")
```suggestion
        q = Q()
        
        if brand_id or type_id:
            q &= Q(brand=brand_id) 
            
        if type_id:
            q &= Q(type=type_id)
```

2021-08-06 05:35 UTC, Kang-kyunghun commented on products/views.py
> +            } for product in products.order_by(filter)]
```suggestion
        items = [{
                "id"          : product.id,
                "name"        : product.name,
                "price"       : product.price,
                "thumbnail"   : product.thumbnail,
                "like_number" : product.like_number
            } for product in Product.object.filter(q).order_by(filter)]
```
1. 조건문에서는 filter에 대한 조건만 만듭니다. 그리고 완성된 조건을 filter에 넣어줍니다. 만약에 어떠한 조건문도 통과하지 못 하면 빈 Q가 들어가게 되고 이는 all()과 같은 효과를 나타냅니다.
2. 만약에 filter에 order_by 할 수 없는 값이 들어 올 때는 어떻게 될까요? 
3. Q 객체 말고도 dictionary를 이용하여 filter의 인자를 결정하는 방법이 있습니다. 이거는 적용하라는 것은 아니고 알고 있으면 도음이 될 것 같아서 알려드립니다. 한 번 찾아보세요~

2021-08-08 03:28 UTC, Kang-kyunghun requested changes

2021-08-08 03:28 UTC, Kang-kyunghun commented on products/urls.py
> +    path("/catalog", ProductsView.as_view()),
```suggestion
    path("", ProductsView.as_view()),
```
8000/products 까지만 해도 충부히 restful 할 것 같습니다.
이 부분만 수정하면 이제 될 것 같아요.

2021-08-09 01:25 UTC, Kang-kyunghun commented
고생하셨습니다~~ 👍

2021-08-09 01:25 UTC, merged