Add: members views SignInView 생성
wecode-bootcamp-korea/23-1st-ChickenFood-backend pull request #5
Opened 2021-08-06 04:00 UTC by shm39

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 뷰 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- members/views.py SignInView 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 로그인 POSTMAN
![image](https://user-images.githubusercontent.com/54498071/128453963-d9ea297c-48eb-422f-86d6-f6352b229046.png)
 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-06 05:40 UTC, Kang-kyunghun requested changes

2021-08-06 05:40 UTC, Kang-kyunghun commented on members/views.py
> +            data['member'] = data['member'].replace("-", "")
```suggestion
            member = data['member'].replace("-", "")
```

2021-08-06 05:40 UTC, Kang-kyunghun commented on members/views.py
> +                login_phone_number=""
```suggestion
        
```

2021-08-06 05:40 UTC, Kang-kyunghun commented on members/views.py
> +                return JsonResponse({"message": "INVALID_MEMBER"}, status=401)
유저 정보 확인과 비밀번호 확인을 둘로 나누어 주세요.

2021-08-06 05:47 UTC, shm39 commented on members/views.py
> +                return JsonResponse({"message": "INVALID_MEMBER"}, status=401)
넵 알겠습니다.

2021-08-08 03:35 UTC, Kang-kyunghun requested changes

2021-08-08 03:35 UTC, Kang-kyunghun commented on members/views.py
> +                return JsonResponse({"message": "INVALID_MEMBER"}, status=401)
```suggestion
            if not Member.objects.filter(Q(name=member) | Q(phone_number=member)).exists():
                return JsonResponse({"message": "INVALID_MEMBER"}, status=401)
                
            if not bcrypt.checkpw(data['password'].encode('utf-8'), Member.objects.get(Q(name=login_name) | Q(phone_number=login_phone_number)).password.encode('utf-8')):
                return JsonResponse({"message": "INVALID_MEMBER"}, status=401)
```
if문 사이에 공백 추가해 주세요.

2021-08-08 03:35 UTC, Kang-kyunghun commented on members/views.py
> +            token = jwt.encode({'id': Member.objects.get(Q(name=login_name) | Q(phone_number=login_phone_number)).id}, SECRET_KEY, algorithm='HS256')
```suggestion
            q= Q(name=login_name) | Q(phone_number=login_phone_number)
            ...
            token = jwt.encode({'id': Member.objects.get(q).id}, SECRET_KEY, algorithm='HS256')
```
Q을 사용한 부분이 반복되고 길어서 가독성이 떨어집니다. 조건(Q)에 대해서 미리 선언한 뒤에 사용하면 좋을 것 같아요.

2021-08-08 03:35 UTC, Kang-kyunghun commented on members/views.py
> +            return JsonResponse({"mesage": "INVALID_VALUE"}, status=400)
Exception으로 에러 처리하는 것은 안 좋은 방법입니다. 모든 에러에 대해 예외를 발생 시키므로 에러를 특정 짓기가 힘듭니다.
지양해 주세요.

2021-08-08 04:12 UTC, shm39 commented on members/views.py
> +            return JsonResponse({"mesage": "INVALID_VALUE"}, status=400)
넵 수정하겠습니다.

2021-08-08 04:12 UTC, shm39 commented on members/views.py
> +            token = jwt.encode({'id': Member.objects.get(Q(name=login_name) | Q(phone_number=login_phone_number)).id}, SECRET_KEY, algorithm='HS256')
넵 수정하겠습니다.

2021-08-09 01:23 UTC, Kang-kyunghun requested changes

2021-08-09 01:23 UTC, Kang-kyunghun commented on members/views.py
> +        data = json.loads(request.body)
회원가입은 merge가 되었는데 왜 코드가 같이 올라 왔을까요??

2021-08-09 01:23 UTC, Kang-kyunghun commented on members/views.py
> +        member = data['member'].replace("-", "")
해당 코드에 의해 keyerror가 발생할 수 있습니다. keyerror에 대한 예외처리 추가해 주세요.

2021-08-09 02:05 UTC, shm39 commented on members/views.py
> +        data = json.loads(request.body)
SignInView 의 Exception을 없애면서 SignUpView의 Exception도 없애줬고, 텝을 수정하였습니다.

2021-08-09 05:52 UTC, Kang-kyunghun commented
리뷰 반영이 다 되지 않았습니다.

2021-08-09 05:55 UTC, shm39 commented
> 리뷰 반영이 다 되지 않았습니다.

2021-08-09 06:02 UTC, shm39 reviewed
> 리뷰 반영이 다 되지 않았습니다.

KeyError는 바로 위에서 data.get('member')를 이용하여 예외처리했습니다.

2021-08-09 06:02 UTC, shm39 commented on members/views.py
> +        if not (data.get('member') and data.get('password')):
KeyError는 data['member'] 방식으로 접근했을때, dictionary의 key이 존재하지 않으면 나오는 Error로 알고 있습니다. 때문에 data.get('member')로 비어있는 경우를 예외처리 했는데 이 상황에서도 KeyError가 발생할 수 있을까요?

2021-08-09 08:58 UTC, Kang-kyunghun commented
LGTM~!!

2021-08-09 08:58 UTC, merged