[23기 손호민] Add: login_decorator 로그인 데코레이터 생성
wecode-bootcamp-korea/23-1st-ChickenFood-backend pull request #6
Opened 2021-08-06 05:42 UTC by shm39

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 데코레이터 생성

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- members/utils.py login_decorator 생성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-  

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-08 03:30 UTC, Kang-kyunghun requested changes

2021-08-08 03:30 UTC, Kang-kyunghun commented on members/utils.py
> +            return JsonResponse({"message": "INVALID_AUTHORIZATION"}, status=400)
Exception으로 에러처리 할 경우 모든 예외에 대해서 예외처리를 하게 됩니다. 이렇게 되면 어떤 상황에서 에러가 나는지 정확하게 판단하기 힘듭니다. 명확한 예외처리가 아니면 사용하지 말아주세요.

2021-08-08 04:15 UTC, shm39 commented on members/utils.py
> +            return JsonResponse({"message": "INVALID_AUTHORIZATION"}, status=400)
네. 수정하겠습니다.

2021-08-09 01:24 UTC, Kang-kyunghun requested changes

2021-08-09 01:24 UTC, Kang-kyunghun commented on members/utils.py
> +            member         = Member.objects.get(id=payload['id'])
user가 존재하지 않을 경우에 대해 예외처리 추가해 주세요.

2021-08-09 05:58 UTC, Kang-kyunghun requested changes

2021-08-09 05:58 UTC, Kang-kyunghun commented on members/utils.py
> +                return JsonResponse({"message": "INVALID_MEMBER"}, status=400)
1. 존재 유무를 판단할 때는 exists() method을 활용해 주세요. exists() method는 실제 데이터가 아닌 True/False만 반환하기 때문에 더 효율적입니다.
2. 로직상 id가 존재하지 않아야 INVALID_MEMBER이지 않을까요?

2021-08-09 06:12 UTC, shm39 commented on members/utils.py
> +                return JsonResponse({"message": "INVALID_MEMBER"}, status=400)
꼼꼼하게 확인하지 못했네요. 확이하여 수정하겠습니다.

2021-08-09 08:58 UTC, Kang-kyunghun commented
LGTM~!

2021-08-09 08:58 UTC, merged